prefix rml: <http://w3id.org/rml/>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#>

SELECT DISTINCT *
WHERE {
  ?triples_map_id rml:logicalSource ?_source .
  # typhon-rml identifier
  # remember to re add
  OPTIONAL {
    ?_source rml:source ?data_source .
  }
  OPTIONAL {
    ?data_source a dcat:Distribution .
    ?data_source dcat:accessURL ?access_url . # downloadURL would be better
  }
# When Source has rml:FilePath
  OPTIONAL {
    ?data_source a rml:FilePath .
    ?data_source rml:root ?root_folder .
    ?data_source rml:path ?path .
  }
# TODO Handle relative paths
  OPTIONAL {
    ?data_source a rml:RelativePathSource .
    ?data_source rml:root ?root_folder .
    ?data_source rml:path ?path .
  }
  OPTIONAL {
    ?_source rml:referenceFormulation ?ref_form .
  } # missing in BC page
  OPTIONAL {
    ?_source rml:iterator ?iterator .
  }
  OPTIONAL {
    ?_source rml:query ?query .
  }
# TODO Handle rml:null
  OPTIONAL {
    ?data_source a d2rq:Database ;
                 d2rq:jdbcDSN ?jdbcDSN ;
                 d2rq:jdbcDriver ?jdbcDriver ;
                 d2rq:username ?user ;
                 d2rq:password ?password .
  }
}
